---
output: pdf_document
---

# Introduction\label{label1}

This is an example introduction. Let's cite someone here [@Author2016]. And in text as well: @Author2013 says that we can cite people in text. Or we can write the name, and than use the citation thingy to print the year: Blabla states something about something [-@Blabla2010]. Or how about multiple citations [@Author2016; @Author2013]. Or we citation with a little of text around it [for example see @Blabla2010, pp. 92-93].

We can split up the chapter in subsections:

## Subsection

For example, this is a subsection of the introduction. We can also make more subsubsections, but they won't be displayed in the table of contents:

### Subsubsection

There you go, a subsubsection. And just for fun:

#### Subsubsubsection

And some text for this subsubsubsection. Let's do another subsection:

## Another subsection

Some text... And finally, a subsection that won't be numbered or shown in the table of contents:

\subsection*{Kind of invisible subsection}

This section  won't be displayed in the table of contents. It also won't be numbered. Now let's move on to the methods.